---
- name: set vars
  set_fact:
    docker_image: '{{ role_sonarr_image }}'
    docker_container: '{{ role_sonarr_container }}'
    docker_puid: '{{ role_sonarr_puid }}'
    docker_pgid: '{{ role_sonarr_pgid }}'
    docker_tz: '{{ role_sonarr_tz }}'
    docker_dir: '{{ role_sonarr_dir }}/config'
    docker_network: '{{ role_sonarr_network }}'
    sonarr_media_dir: '{{ role_sonarr_media_dir }}'

- name: Create directory
  ansible.builtin.file:
    path: '{{docker_dir}}'
    state: directory
    owner: '{{ docker_puid }}'
    group: '{{ docker_pgid }}'
    mode: 0755

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create network
  community.docker.docker_network:
    name: "{{ docker_network }}"
    driver_options:
          com.docker.network.bridge.name: "br-{{ docker_network }}"

- name: Create sonarr container
  community.docker.docker_container:
    image: '{{ docker_image }}'
    volumes:
     - '{{ docker_dir }}:/config:Z'
     - '{{ sonarr_media_dir }}:/media:Z'
     
    env:
      PUID: '{{ docker_puid }}'
      PGID: '{{ docker_pgid }}'
      TZ: '{{ docker_tz }}'
    name: "{{ docker_container }}"
    networks:
     - name: "{{ docker_network }}"
    restart_policy: unless-stopped
    state: started
  when: 
    pulled.changed
    or
    result.exists == false
